version: "1.0"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  mysql:
    image: mysql:8.2
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
