server:
  port: 8002
databases:
  - user: admin
    password: admin
    host: localhost
    dbName: shopDev
  - user: role
    password: role
    host: localhost
    dbName: role
security:
  jwt:
    key: abc123
